# Generated by Django 5.1.6 on 2025-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_userworkspace_role_userapartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapartment',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], default='tenant', max_length=20),
        ),
    ]
