# Generated by Django 5.1.6 on 2025-02-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profile Image'),
        ),
    ]
